version: '3'

services:
  backend:
    container_name: Earth_API
    build:
      context: ./backend
      dockerfile: Dockerfile

    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code

  frontend:
    container_name: Earth_front
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3006:3006"
    expose:
      - 3006
  
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_DB=game_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: db
    volumes:
      - ./backend/app/database:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
